language: python
sudo: false

branches:
  only:
    - master

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.5  CONDA_PY=35
    - python=3.6  CONDA_PY=36
  #env: not sure what this does

before_install:
install:
script:
after_success:
